stretch: workaround missing gnupg
Error: gnupg, gnupg2 and gnupg1 do not seem to be installed,
Error: but apt-key requires gnupg, gnupg2 or gnupg1 for this operation.

Change-Id: Ib6f3be407a6fed1b182b3d3b0851e21da0ffeb31
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>