LLP: Fix Missing package
When installing pip packages we need llfi-dev otherwise we get a fatal
error: ffi.h: No such file or directory

Change-Id: Ia98558824c47222970f04d9332b6ce6540ee467d